# Generated by Django 3.1.1 on 2020-12-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0002_auto_20201201_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxondefiner',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='definer.taxa'),
        ),
    ]
