# Generated by Django 3.1.1 on 2020-12-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0003_taxondefiner_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxondefiner',
            name='taxon',
        ),
    ]
