# Generated by Django 3.1.1 on 2020-12-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0004_remove_taxondefiner_taxon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxondefiner',
            old_name='description',
            new_name='definer_description',
        ),
        migrations.AddField(
            model_name='taxondefiner',
            name='full_description',
            field=models.TextField(blank=True),
        ),
    ]
