# Generated by Django 3.1.1 on 2021-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0009_taxonsearch_moss_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonsearch',
            name='moss_class',
            field=models.CharField(blank=True, default='Bryopsida', max_length=150),
        ),
    ]
