# Generated by Django 3.1.1 on 2021-01-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0013_auto_20210105_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonsearch',
            name='activ',
        ),
    ]
