# Generated by Django 3.1.1 on 2021-01-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0014_remove_taxonsearch_activ'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxa',
            name='identifier',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='taxonsearch',
            name='activation',
            field=models.CharField(blank=True, choices=[('Act', 'Act'), ('Deact', 'Deact'), ('Frozen', 'Frozen')], default='Deact', max_length=30),
        ),
    ]
