# Generated by Django 3.1.1 on 2021-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0015_auto_20210125_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonsearch',
            name='activation',
            field=models.CharField(blank=True, choices=[('Act', 'Act'), ('Deact', 'Deact'), ('Frozen', 'Frozen')], default='Act', max_length=30),
        ),
    ]
