# Generated by Django 3.1.1 on 2021-02-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0016_auto_20210131_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonsearch',
            name='division',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='taxonsearch',
            name='activation',
            field=models.CharField(blank=True, choices=[('Act', 'Act'), ('Deact', 'Deact'), ('Frozen', 'Frozen')], default='Actz', max_length=30),
        ),
        migrations.AlterField(
            model_name='taxonsearch',
            name='moss_class',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
