# Generated by Django 3.1.1 on 2021-02-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0017_auto_20210204_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonsearch',
            name='division',
            field=models.CharField(blank=True, default='Bryophita', max_length=150),
        ),
    ]
