# Generated by Django 3.1.1 on 2021-02-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0022_auto_20210212_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxondefiner',
            name='tax',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.DeleteModel(
            name='TaxonDefiner',
        ),
    ]
