# Generated by Django 3.1.1 on 2020-12-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('definer', '0007_remove_taxondefiner_taxon_accordance'),
        ('moss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='definer.taxa'),
        ),
    ]
