# Generated by Django 3.1.1 on 2020-12-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0003_auto_20201203_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpeciesImg',
            new_name='SpeciesImages',
        ),
        migrations.RenameField(
            model_name='genusimages',
            old_name='species_attach',
            new_name='taxon',
        ),
        migrations.RenameField(
            model_name='speciesimages',
            old_name='species_attach',
            new_name='taxon',
        ),
        migrations.RenameField(
            model_name='subclassimages',
            old_name='species_attach',
            new_name='taxon',
        ),
        migrations.RemoveField(
            model_name='subclass',
            name='img',
        ),
    ]
