# Generated by Django 3.1.1 on 2020-12-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0004_auto_20201203_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='definer_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='OrderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='order')),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moss.order')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='family')),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moss.family')),
            ],
        ),
        migrations.CreateModel(
            name='ClassImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='class')),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moss.class')),
            ],
        ),
    ]
