# Generated by Django 3.1.1 on 2020-12-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0005_auto_20201206_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclass',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
