# Generated by Django 3.1.1 on 2020-12-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0007_auto_20201210_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='parent_class',
            new_name='parent_taxon',
        ),
        migrations.RenameField(
            model_name='genus',
            old_name='parent_class',
            new_name='parent_taxon',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='parent_class',
            new_name='parent_taxon',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='parent_class',
            new_name='parent_taxon',
        ),
        migrations.RenameField(
            model_name='subclass',
            old_name='parent_class',
            new_name='parent_taxon',
        ),
    ]
