# Generated by Django 3.1.1 on 2021-01-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0009_auto_20201214_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxononmap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='map_images'),
        ),
        migrations.AlterField(
            model_name='taxononmap',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moss.species'),
        ),
    ]
