# Generated by Django 3.1.1 on 2021-01-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0012_auto_20210128_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomepageImages',
        ),
    ]
