# Generated by Django 3.1.1 on 2021-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0014_homepageimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimages',
            name='img_field',
            field=models.CharField(blank=True, choices=[], max_length=30),
        ),
    ]
