# Generated by Django 3.1.1 on 2021-01-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0015_homepageimages_img_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclass',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
