# Generated by Django 3.1.1 on 2021-01-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0016_auto_20210128_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclass',
            name='img',
            field=models.ImageField(blank=True, default='None', null=True, upload_to=''),
        ),
    ]
