# Generated by Django 3.1.1 on 2021-01-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0018_auto_20210128_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimages',
            name='test_field',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepageimages',
            name='img_field',
            field=models.TextField(blank=True),
        ),
    ]
