# Generated by Django 3.1.1 on 2021-01-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0019_auto_20210131_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageimages',
            name='test_field',
        ),
    ]
