# Generated by Django 3.1.1 on 2021-02-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0021_auto_20210203_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='division')),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moss.division')),
            ],
        ),
    ]
