# Generated by Django 3.1.1 on 2021-02-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0022_divisionimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='parent_taxon',
            field=models.CharField(default='Plantae', max_length=50),
        ),
    ]
