# Generated by Django 3.1.1 on 2021-02-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0023_division_parent_taxon'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='parent_taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moss.genus'),
        ),
    ]
